name = "health-v2-api"
main = "src/index.ts"
compatibility_date = "2026-02-08"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "health-v2-db"
database_id = "82401b3e-7122-4ff1-8b92-6b1577071a26"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "health-v2-uploads"
